import os

ci = os.environ.get('CI', None)
github_token = os.environ.get('GITHUB_TOKEN', None)
github_action = os.environ.get('GITHUB_ACTION', None)
github_action_path = os.environ.get('GITHUB_ACTION_PATH', None)
github_action_repository = os.environ.get('GITHUB_ACTION_REPOSITORY', None)
github_actions = os.environ.get('GITHUB_ACTIONS', None)
github_actor = os.environ.get('GITHUB_ACTOR', None)
github_api_url = os.environ.get('GITHUB_API_URL', None)
github_base_ref = os.environ.get('GITHUB_BASE_REF', None)
github_env = os.environ.get('GITHUB_ENV', None)
github_event_name = os.environ.get('GITHUB_EVENT_NAME', None)
github_event_path = os.environ.get('GITHUB_EVENT_PATH', None)
github_graphql_url = os.environ.get('GITHUB_GRAPHQL_URL', None)
github_head_ref = os.environ.get('GITHUB_HEAD_REF', None)
github_job = os.environ.get('GITHUB_JOB', None)
github_path = os.environ.get('GITHUB_PATH', None)
github_ref = os.environ.get('GITHUB_REF', None)
github_ref_name = os.environ.get('GITHUB_REF_NAME', None)
github_ref_protected = os.environ.get('GITHUB_REF_PROTECTED', None)
github_ref_type = os.environ.get('GITHUB_REF_TYPE', None)
github_repository = os.environ.get('GITHUB_REPOSITORY', None)
github_repository_owner = os.environ.get('GITHUB_REPOSITORY_OWNER', None)
github_retention_days = os.environ.get('GITHUB_RETENTION_DAYS', None)
github_run_attempt = os.environ.get('GITHUB_RUN_ATTEMPT', None)
github_run_id = os.environ.get('GITHUB_RUN_ID', None)
github_run_number = os.environ.get('GITHUB_RUN_NUMBER', None)
github_server_url = os.environ.get('GITHUB_SERVER_URL', None)
github_sha = os.environ.get('GITHUB_SHA', None)
github_step_summary = os.environ.get('GITHUB_STEP_SUMMARY', None)
github_workflow = os.environ.get('GITHUB_WORKFLOW', None)
github_workspace = os.environ.get('GITHUB_WORKSPACE', None)
runner_arch = os.environ.get('RUNNER_ARCH', None)
runner_debug = os.environ.get('RUNNER_DEBUG', None)
runner_name = os.environ.get('RUNNER_NAME', None)
runner_os = os.environ.get('RUNNER_OS', None)
runner_temp = os.environ.get('RUNNER_TEMP', None)
runner_tool_cache = os.environ.get('RUNNER_TOOL_CACHE', None)


print(f'ci and github_actions: {ci and github_actions}')
print(f'{github_server_url}/{github_repository}')
print(f'github_sha: {github_sha}')

print('')
print('')

print(f'CI = {ci}')
print(f'GITHUB_TOKEN = {github_token}')
print(f'GITHUB_ACTION = {github_action}')
print(f'GITHUB_ACTION_PATH = {github_action_path}')
print(f'GITHUB_ACTION_REPOSITORY = {github_action_repository}')
print(f'GITHUB_ACTIONS = {github_actions}')
print(f'GITHUB_ACTOR = {github_actor}')
print(f'GITHUB_API_URL = {github_api_url}')
print(f'GITHUB_BASE_REF = {github_base_ref}')
print(f'GITHUB_ENV = {github_env}')
print(f'GITHUB_EVENT_NAME = {github_event_name}')
print(f'GITHUB_EVENT_PATH = {github_event_path}')
print(f'GITHUB_GRAPHQL_URL = {github_graphql_url}')
print(f'GITHUB_HEAD_REF = {github_head_ref}')
print(f'GITHUB_JOB = {github_job}')
print(f'GITHUB_PATH = {github_path}')
print(f'GITHUB_REF = {github_ref}')
print(f'GITHUB_REF_NAME = {github_ref_name}')
print(f'GITHUB_REF_PROTECTED = {github_ref_protected}')
print(f'GITHUB_REF_TYPE = {github_ref_type}')
print(f'GITHUB_REPOSITORY = {github_repository}')
print(f'GITHUB_REPOSITORY_OWNER = {github_repository_owner}')
print(f'GITHUB_RETENTION_DAYS = {github_retention_days}')
print(f'GITHUB_RUN_ATTEMPT = {github_run_attempt}')
print(f'GITHUB_RUN_ID = {github_run_id}')
print(f'GITHUB_RUN_NUMBER = {github_run_number}')
print(f'GITHUB_SERVER_URL = {github_server_url}')
print(f'GITHUB_SHA = {github_sha}')
print(f'GITHUB_STEP_SUMMARY = {github_step_summary}')
print(f'GITHUB_WORKFLOW = {github_workflow}')
print(f'GITHUB_WORKSPACE = {github_workspace}')
print(f'RUNNER_ARCH = {runner_arch}')
print(f'RUNNER_DEBUG = {runner_debug}')
print(f'RUNNER_NAME = {runner_name}')
print(f'RUNNER_OS = {runner_os}')
print(f'RUNNER_TEMP = {runner_temp}')
print(f'RUNNER_TOOL_CACHE = {runner_tool_cache}')
