name: Create Environment

permissions:
  id-token: write
  contents: read

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency:
  group: ${{ github.event.number || github.ref_name }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'

    outputs:
      type: ${{ steps.setup.outputs.type }}
      name: ${{ steps.setup.outputs.name }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        id: setup
        uses: colbylwilliams/deployment-environments@azd

      - run: echo "Type ${{ steps.setup.outputs.type }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "Name ${{ steps.setup.outputs.name }}" >> $GITHUB_STEP_SUMMARY

  create:
    name: Create Environment (${{ needs.setup.outputs.type }})
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'

    needs: setup

    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Setup Environment
        uses: colbylwilliams/deployment-environments@azd

      - name: Website
        id: website
        run: echo "url=https://$ADE_NAME.azurewebsites.net" >> $GITHUB_OUTPUT

      - name: Setup
        run: |
          echo "### Deployment Successful :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- View the [website](${{ steps.website.outputs.url }})" >> $GITHUB_STEP_SUMMARY
          echo "- View resources in the [Azure Portal]($ADE_PORTAL_URL)" >> $GITHUB_STEP_SUMMARY
          echo '---' >> $GITHUB_STEP_SUMMARY
          echo "### Use the [azd cli](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/) to deploy the application" >> $GITHUB_STEP_SUMMARY
          echo "1. First, make sure azd is configured azd to use DevCenter:" >> $GITHUB_STEP_SUMMARY
          echo '```sh' >> $GITHUB_STEP_SUMMARY
          echo "azd config set platform.type devcenter" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '2. In the root of the cloned repsitory, select the `${{ needs.setup.outputs.name }}` environment created for this ${{ github.event_name == 'pull_request' && 'PR' || 'branch' }}:' >> $GITHUB_STEP_SUMMARY
          echo '```sh' >> $GITHUB_STEP_SUMMARY
          echo "azd env select $ADE_NAME" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "3. When you make changes, deploy them to the new environment:" >> $GITHUB_STEP_SUMMARY
          echo '```sh' >> $GITHUB_STEP_SUMMARY
          echo "azd deploy" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Add Link to Pull Request
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            const webUrl = '${{ steps.website.outputs.url }}'
            const portalUrl = 'https://portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/resource/subscriptions/4adee40b-e41a-48a8-92be-256e27b9bea5/resourceGroups/e-shop-ci-pr-70-igntdmo'

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### Deployment Successful :rocket:\n- View the [website](${webUrl})\n- View resources in the [Azure Portal](${portalUrl})`,
            });

  test:
    name: Test Environment
    if: github.event_name == 'pull_request'

    needs:
      - setup
      - create

    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    uses: ./.github/workflows/env_test.yml
    with:
      name: ${{ needs.setup.outputs.name }}
      type: ${{ needs.setup.outputs.type }}
      # url: ${{ needs.create.outputs.url }}
      # subscription: ${{ needs.create.outputs.subscription }}
      # resource-group: ${{ needs.create.outputs.resource-group }}
    secrets: inherit
