name: ADE

on:
  push:
  pull_request:

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        id: setup
        uses: colbylwilliams/deployment-environments@main

      - run: echo "Type ${{ steps.setup.outputs.type }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "Name ${{ steps.setup.outputs.name }}" >> $GITHUB_STEP_SUMMARY

      - run: echo "${{ github }}"

      - run: echo "Environment Variables:" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_TENANT $ADE_TENANT" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_SUBSCRIPTION $ADE_SUBSCRIPTION" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_RESOURCE_GROUP $ADE_RESOURCE_GROUP" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_RESOURCE_GROUP_ID $ADE_RESOURCE_GROUP_ID" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_EXISTS $ADE_EXISTS" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_CREATED $ADE_CREATED" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_PORTAL_URL $ADE_PORTAL_URL" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_NAME $ADE_NAME" >> $GITHUB_STEP_SUMMARY
      - run: echo "  ADE_TYPE $ADE_TYPE" >> $GITHUB_STEP_SUMMARY

      - run: echo 'Outputs:' >> $GITHUB_STEP_SUMMARY
      - run: echo "  tenant ${{ steps.setup.outputs.tenant }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  subscription ${{ steps.setup.outputs.subscription }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  resource-group ${{ steps.setup.outputs.resource-group }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  resource-group-id ${{ steps.setup.outputs.resource-group-id }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  exists ${{ steps.setup.outputs.exists }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  created ${{ steps.setup.outputs.created }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  portal-url ${{ steps.setup.outputs.portal-url }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  name ${{ steps.setup.outputs.name }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "  type ${{ steps.setup.outputs.type }}" >> $GITHUB_STEP_SUMMARY
