name: ADE

on:
  push:
  pull_request:

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        id: setup
        uses: colbylwilliams/deployment-environments@azd

      # - run: echo "${{ github }}"

      - run: |
          echo "### Outputs:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Name              | Value                                        |" >> $GITHUB_STEP_SUMMARY
          echo "| ----------------- | -------------------------------------------- |" >> $GITHUB_STEP_SUMMARY
          echo "| tenant            | ${{ steps.setup.outputs.tenant }}            |" >> $GITHUB_STEP_SUMMARY
          echo "| subscription      | ${{ steps.setup.outputs.subscription }}      |" >> $GITHUB_STEP_SUMMARY
          echo "| resource-group    | ${{ steps.setup.outputs.resource-group }}    |" >> $GITHUB_STEP_SUMMARY
          echo "| resource-group-id | ${{ steps.setup.outputs.resource-group-id }} |" >> $GITHUB_STEP_SUMMARY
          echo "| exists            | ${{ steps.setup.outputs.exists }}            |" >> $GITHUB_STEP_SUMMARY
          echo "| created           | ${{ steps.setup.outputs.created }}           |" >> $GITHUB_STEP_SUMMARY
          echo "| portal-url        | ${{ steps.setup.outputs.portal-url }}        |" >> $GITHUB_STEP_SUMMARY
          echo "| name              | ${{ steps.setup.outputs.name }}              |" >> $GITHUB_STEP_SUMMARY
          echo "| type              | ${{ steps.setup.outputs.type }}              |" >> $GITHUB_STEP_SUMMARY
          echo "| devcenter         | ${{ steps.setup.outputs.devcenter }}         |" >> $GITHUB_STEP_SUMMARY
          echo "| project           | ${{ steps.setup.outputs.project }}           |" >> $GITHUB_STEP_SUMMARY
          echo "| definition        | ${{ steps.setup.outputs.definition }}        |" >> $GITHUB_STEP_SUMMARY
          echo "| parameters        | ${{ steps.setup.outputs.parameters }}        |" >> $GITHUB_STEP_SUMMARY

      - run: |
          echo "### Environment Variables:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Name                  | Value                  |" >> $GITHUB_STEP_SUMMARY
          echo "| --------------------- | ---------------------- |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_TENANT            | $ADE_TENANT            |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_SUBSCRIPTION      | $ADE_SUBSCRIPTION      |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_RESOURCE_GROUP    | $ADE_RESOURCE_GROUP    |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_RESOURCE_GROUP_ID | $ADE_RESOURCE_GROUP_ID |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_EXISTS            | $ADE_EXISTS            |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_CREATED           | $ADE_CREATED           |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_PORTAL_URL        | $ADE_PORTAL_URL        |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_NAME              | $ADE_NAME              |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_TYPE              | $ADE_TYPE              |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_DEVCENTER         | $ADE_DEVCENTER         |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_PROJECT           | $ADE_PROJECT           |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_DEFINITION        | $ADE_DEFINITION        |" >> $GITHUB_STEP_SUMMARY
          echo "| ADE_PARAMETERS        | $ADE_PARAMETERS        |" >> $GITHUB_STEP_SUMMARY

      - run: |
          echo "### azd environment variables:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Name                                   | Value                                   |" >> $GITHUB_STEP_SUMMARY
          echo "| -------------------------------------- | --------------------------------------- |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_ENV_NAME                         | $AZURE_ENV_NAME                         |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_DEVCENTER_NAME                   | $AZURE_DEVCENTER_NAME                   |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_DEVCENTER_PROJECT                | $AZURE_DEVCENTER_PROJECT                |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_DEVCENTER_CATALOG                | $AZURE_DEVCENTER_CATALOG                |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_DEVCENTER_ENVIRONMENT_DEFINITION | $AZURE_DEVCENTER_ENVIRONMENT_DEFINITION |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_DEVCENTER_ENVIRONMENT_TYPE       | $AZURE_DEVCENTER_ENVIRONMENT_TYPE       |" >> $GITHUB_STEP_SUMMARY
          echo "| AZURE_DEVCENTER_ENVIRONMENT_USER       | $AZURE_DEVCENTER_ENVIRONMENT_USER       |" >> $GITHUB_STEP_SUMMARY
