name: Build Containers

on:
  push:
    branches: [main]

env:
  IMAGE_REPO: ${{ github.repository }}
  IMAGE_VERSION: 0.0.1
  IMAGE_REGISTRY: ghcr.io

jobs:
  core:
    name: Build Core
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - runner
        uses: docker/build-push-action@v2
        with:
          context: ./core
          file: ./core/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_REPO }}/core:latest
            ${{ env.IMAGE_REPO }}/core:${{ env.IMAGE_VERSION }}

  # runner:
  #   name: Build Runner
  #   runs-on: ubuntu-latest
  #   needs: [core]
  #   permissions:
  #     contents: read
  #     packages: write

  #   strategy:
  #     max-parallel: 5
  #     matrix:
  #       runner: ['arm']

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Docker Login
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{ env.IMAGE_REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push Docker image - ${{ matrix.runner }}
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./${{ matrix.runner }}
  #         file: ./${{ matrix.runner }}/Dockerfile
  #         platforms: linux/amd64
  #         push: ${{ github.event_name != 'pull_request' }}
  #         tags: |
  #           ${{ env.IMAGE_REPO }}/${{ matrix.runner }}:latest
  #           ${{ env.IMAGE_REPO }}/${{ matrix.runner }}:${{ env.IMAGE_VERSION }}
