name: Create Environment

permissions:
  id-token: write
  contents: read

on:
  create:
  pull_request:
    types: [opened, reopened]

concurrency:
  group: ${{ github.event.number || github.ref_name }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        id: setup
        uses: colbylwilliams/deployment-environments@main

      - run: echo "Type ${{ steps.setup.outputs.type }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "Name ${{ steps.setup.outputs.name }}" >> $GITHUB_STEP_SUMMARY
