name: defaults

on: workflow_dispatch

jobs:
  check:
    runs-on:
      labels: ubuntu-latest
      group: Default
    steps:
      - run: echo "$THE_OTHER_THING_A"
        env:
         THE_OTHER_THING_A: ${{ vars.COPILOT_AGENT_FIREWALL_ENABLED || true }}

      - run: echo "$THE_OTHER_THING_B"
        env:
         THE_OTHER_THING_B: ${{ vars.COPILOT_AGENT_FIREWALL_ENABLED || 'true' }}
