name: Setup Demo

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: 'The root name of the branches (number will be appended unless day-of).'
        default: basket-update
      go-time:
        type: boolean
        required: true
        description: 'Only check this for the day-of setup'
        default: false

env:
  BRANCH_NAME: "${{ inputs.name }}${{ inputs.go-time && '' || github.run_number }})"

run-name: Setup Demo ("${{ inputs.name }}${{ inputs.go-time && '' || github.run_number }})")

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world $BRANCH_NAME"
