name: Setup Demo

on:
  workflow_dispatch:
    inputs:
      go-time:
        type: boolean
        required: true
        description: 'Only check this for the day-of setup'
        default: false
      name:
        type: string
        required: true
        description: "The root name of the the branches. Unless it's the day-of, this a number will be appended to the end."
        default: basket-update

env:
  BRANCH_NAME: "${{ inputs.name }}${{ inputs.go-time && '' || github.run_number }})"

run-name: Setup Demo ("${{ inputs.name }}${{ inputs.go-time && '' || github.run_number }})")

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world $BRANCH_NAME"
