name: Setup Demo

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: 'The root name of the branches (number will be appended unless day-of).'
        default: basket-update
      go-time:
        type: boolean
        required: true
        description: 'Only check this for the day-of setup'
        default: false

run-name: Setup Demo ${{ inputs.name }}${{ inputs.go-time && '' || github.run_number }}

jobs:
  branch-a:
    name: branch ${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: ['a', 'b']

    env:
      BRANCH_NAME: "${{ inputs.name }}${{ inputs.go-time && '' || github.run_number }}${{ matrix.branch }}"
      COMMIT_MESSAGE: "updates banner for weekend sale ${{ inputs.go-time && '' || github.run_number }}"
      PR_TITLE: "[${{ matrix.branch }}] Banner update for weekend sale ${{ inputs.go-time && '' || github.run_number }}"

    steps:
      - uses: actions/checkout@v3

      - name: git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: git checkout branch-a
        run: |
          git checkout -b $BRANCH_NAME

      - name: break it
        run: python3 ./github/scripts/demo.py --branch ${{ matrix.branch }}"

      - name: commit and push
        run: |
          git commit -a -m "$COMMIT_MESSAGE"
          git push origin $BRANCH_NAME

      - name: create PR
        run: gh pr create -B main -H $BRANCH_NAME --title $PR_TITLE --fill
