name: version

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: GIT_HASH=$(git rev-parse --short "$GITHUB_SHA") && echo "version=$GITHUB_REF_NAME-$GIT_HASH" >> $GITHUB_OUTPUT
        working-directory: ./
        id: version

      - run: echo "foo:${{ steps.version.outputs.version }}"
  
