name: version

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "foo:${{ github.head_ref }}.${{ github.sha }}"
  
