name: version

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "foo:$GITHUB_REF_NAME-$GIT_HASH"
  
