name: Run on Push

on:
  push:

env:
  RANDOM_ENV: 'foo'

jobs:
  ensure_secrets:
    name: Ensure Secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secret: ['${{ secrets.MY_SECRET }}', '${{ secrets.MY_SECRETB }}']
    steps:
      - name: Check for secret
        shell: python
        run: |
          import sys
          print(${{ matrix.secret }})
          if not ${{ matrix.secret }}:
            print('::error title=Missing Secret::You must create an environment secret or repository secret named MY_SECRET (${{ github.event.repository.html_url }}/settings/secrets/actions)')
            sys.exit()

  do_the_thing:
    name: Do the thing
    runs-on: ubuntu-latest
    needs: ensure_secrets

    steps:
      - name: Echo stuff
        run: echo stuff

      - name: Check for Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        if: env.MY_SECRET == ''
        run: |
          echo "::error title=Missing Secret::You must create an environment secret or repository secret named MY_SECRET (${{ github.event.repository.html_url }}/settings/secrets/actions)"
          exit 1
