name: Run on Push

on:
  push:

env:
  PROVIDER: DEvCenter

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: PROVIDER_NAME=${{ env.PROVIDER }} && IMAGE_NAME=${PROVIDER_NAME,,} && echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT
      - run: echo "foo/${{ env.IMAGE_NAME}}"
        env:
          IMAGE_NAME: "provider-${{ steps.setup.outputs.name }}"
