name: Run on Push

on:
  push:

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print GitHub
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: python "./github_env.py"
