name: Run on Push

on:
  push:

env:
  THE_THING: AThingThatIsSet

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "env.THE_THING ${{ env.THE_THING }}"
      - id: setup
        run: echo "lowercase=${${{ env.THE_THING }},,}" >> $GITHUB_OUTPUT
      - run: echo "lowercase=${{ steps.setup.outputs.lowercase }}"
