name: Run on Push

on:
  push:

env:
  THE_THING: AThingThatIsSet

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "env.THE_THING ${{ env.THE_THING }}"
      - id: setup
        run: THING_LOWERCASE=${THE_THING,,} && echo "lowercase=$THING_LOWERCASE" >> $GITHUB_OUTPUT
      - run: echo "lowercase=${{ steps.setup.outputs.lowercase }}"
