name: Version Call

on:
  workflow_call:

jobs:
  builda:
    name: Build A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Install .NET Core
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 6.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Save Version
        id: version
        run: echo "version=$GITVERSION_FULLSEMVER" >> $GITHUB_OUTPUT

      - run: echo "$GITVERSION_FULLSEMVER" >> $GITHUB_STEP_SUMMARY

  buildb:
    name: Build B
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Install .NET Core
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 6.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Save Version
        id: version
        run: echo "version=$GITVERSION_FULLSEMVER" >> $GITHUB_OUTPUT

      - run: echo "$GITVERSION_FULLSEMVER" >> $GITHUB_STEP_SUMMARY

  buildc:
    name: Build C
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Install .NET Core
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 6.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Save Version
        id: version
        run: echo "version=$GITVERSION_FULLSEMVER" >> $GITHUB_OUTPUT

      - run: echo "$GITVERSION_FULLSEMVER" >> $GITHUB_STEP_SUMMARY
